{% set name = "vdms" %}
{% set version = "0.0.21" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vdms-{{ version }}.tar.gz
  sha256: bbb62d3f1a5cdab6b6bd41950942880cc431729313742870eb255a23c5f0381f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python <4.0
    - pip
  run:
    - python <4.0
    - protobuf ==4.24.2

test:
  imports:
    - vdms
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/IntelLabs/vdms
  summary: VDMS Client Module
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
